import { Campus, Post } from "./types";

export const INITIAL_CAMPUSES: Campus[] = [
  {
    id: "bhopal-node",
    name: "MANIT / RGPV Campus Hub",
    city: "Bhopal",
    country: "India",
    developer_github_handle: "campus-dev-bhopal",
    is_verified: true,
    accent_color: "from-blue-600 to-indigo-700",
  },
  {
    id: "polaris-blr",
    name: "Polaris School of Technology",
    city: "Bangalore",
    country: "India",
    developer_github_handle: "nexus-polaris",
    is_verified: true,
    accent_color: "from-cyan-500 to-blue-600",
  },
  {
    id: "iitb-mum",
    name: "Indian Institute of Technology Bombay",
    city: "Mumbai",
    country: "India",
    developer_github_handle: "iitb-tech",
    is_verified: true,
    accent_color: "from-amber-500 to-orange-600",
  },
  {
    id: "stanford-us",
    name: "Stanford University",
    city: "Stanford, CA",
    country: "United States",
    developer_github_handle: "stanford-tree-dev",
    is_verified: true,
    accent_color: "from-red-600 to-rose-700",
  },
  {
    id: "nus-sg",
    name: "National University of Singapore (NUS)",
    city: "Singapore",
    country: "Singapore",
    developer_github_handle: "nus-hackers",
    is_verified: true,
    accent_color: "from-orange-500 to-amber-600",
  },
  {
    id: "oxford-uk",
    name: "University of Oxford",
    city: "Oxford",
    country: "United Kingdom",
    developer_github_handle: "oxford-oxon",
    is_verified: true,
    accent_color: "from-indigo-600 to-blue-800",
  },
  {
    id: "tum-de",
    name: "Technical University of Munich",
    city: "Munich",
    country: "Germany",
    developer_github_handle: "tum-informatics",
    is_verified: true,
    accent_color: "from-blue-700 to-sky-600",
  },
];

export const INITIAL_POSTS: Post[] = [
  // Bhopal Campus Posts
  {
    id: "bhopal-post-1",
    campus_id: "bhopal-node",
    user_name: "Office of the Dean (Academic Affairs)",
    user_role_tag: "admin",
    title: "Official Notification: End Semester Examination Timetable & Admit Cards",
    content: "The final exam timetable for 3rd, 5th, and 7th semester students is released on the academic portal. Hall tickets will be downloadable starting Monday 10:00 AM. Please clear all pending lab records before obtaining signatures.",
    category_tag: "Official Alert",
    upvotes_count: 84,
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(), // 45m ago
    is_sos: false,
    is_anonymous: false,
  },
  {
    id: "bhopal-post-2",
    campus_id: "bhopal-node",
    user_name: "Aero & Robotics Society (ARS)",
    user_role_tag: "club",
    title: "⚡ Hackathon Sprint & Drone Racing Workshop this Weekend!",
    content: "Calling all makers, coders, and pilots! We are hosting a 36-hour IoT & Drone simulation challenge in the Mechanical Block Workshop. Free hardware kits provided for selected teams. Refreshments & stickers included!",
    category_tag: "Fest/Events",
    upvotes_count: 57,
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(), // 3h ago
    is_sos: false,
    is_anonymous: false,
  },
  {
    id: "bhopal-post-3",
    campus_id: "bhopal-node",
    user_name: "Anonymous Student",
    user_role_tag: "student",
    title: "CRITICAL SOS: Need Operating Systems (CS-501) mid-sem cheat sheet / memory management notes",
    content: "Professor announced a surprise quiz on Virtual Memory, Paging, and Page Fault algorithms tomorrow morning! Has anyone compiled clean notes or solved numericals from Galvin? Please save a soul 🙏",
    category_tag: "SOS Query",
    upvotes_count: 46,
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(), // 2h ago
    is_sos: true,
    is_anonymous: true,
    answers: [
      {
        id: "ans-1",
        post_id: "bhopal-post-3",
        user_name: "Aditya Verma (CS Final Year)",
        user_role_tag: "student",
        content: "Here is the Google Drive link with all solved gate questions and Galvin Chapter 9 short notes: https://drive.google.com/drive/folders/exam-prep-os. Focus specifically on FIFO vs LRU page replacement numericals, 100% coming!",
        upvotes_count: 32,
        timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
        is_accepted: true,
      },
      {
        id: "ans-2",
        post_id: "bhopal-post-3",
        user_name: "Anonymous Student",
        user_role_tag: "student",
        content: "Also check NPTEL lecture 24 & 25 summary slides. The numerical on Belady's anomaly always shows up for 5 marks.",
        upvotes_count: 14,
        timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      }
    ]
  },
  {
    id: "bhopal-post-4",
    campus_id: "bhopal-node",
    user_name: "Pooja Deshmukh",
    user_role_tag: "student",
    title: "Found: Silver Casio Scientific Calculator (fx-991EX) in Room 204",
    content: "Found this calculator after the 2 PM Mathematics lecture on the third row bench. It has a tiny anime sticker on the back cover. Drop a message to collect it from Hostel 7 mess counter.",
    category_tag: "Lost & Found",
    upvotes_count: 22,
    timestamp: new Date(Date.now() - 1000 * 60 * 360).toISOString(), // 6h ago
    is_sos: false,
    is_anonymous: false,
  },
  {
    id: "bhopal-post-5",
    campus_id: "bhopal-node",
    user_name: "Competitive Programming Chapter",
    user_role_tag: "club",
    title: "Curated DSA Roadmap for Upcoming Product Company Campus Drives",
    content: "We have mapped out the top 75 LeetCode patterns most frequently asked during campus hiring by tier-1 firms. Repository includes company-wise frequency charts and video walkthroughs.",
    category_tag: "Exam Preparation",
    upvotes_count: 73,
    timestamp: new Date(Date.now() - 1000 * 60 * 720).toISOString(), // 12h ago
    is_sos: false,
    is_anonymous: false,
  },

  // Polaris School of Technology (Bangalore) Posts
  {
    id: "polaris-post-1",
    campus_id: "polaris-blr",
    user_name: "Polaris Academic Directorate",
    user_role_tag: "admin",
    title: "Winter Term Industry Track: Y-Combinator Founder Guest Lecture",
    content: "Join us in the Main Auditorium or via the live campus stream tomorrow at 5:00 PM IST for an exclusive session with YC alumni on 'Architecting AI Agents for Production Scale'. RSVP required via student intranet.",
    category_tag: "Official Alert",
    upvotes_count: 112,
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30m ago
    is_sos: false,
    is_anonymous: false,
  },
  {
    id: "polaris-post-2",
    campus_id: "polaris-blr",
    user_name: "Web3 & Distributed Systems Guild",
    user_role_tag: "club",
    title: "🚀 Polaris Solana Summer Fellowship Selected Cohort Announcement",
    content: "Congratulations to the 12 student builders selected for the summer grants! First sprint meeting happens Wednesday at 7 PM in Maker Lab 2. Demo day set for November.",
    category_tag: "Fest/Events",
    upvotes_count: 65,
    timestamp: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    is_sos: false,
    is_anonymous: false,
  },
  {
    id: "polaris-post-3",
    campus_id: "polaris-blr",
    user_name: "Anonymous Student",
    user_role_tag: "student",
    title: "URGENT SOS: Need immediate accommodation lead near HSR Sector 2 / Koramangala",
    content: "My lease ended unexpectedly and need a room in a 2BHK/3BHK within 15 mins commute of Polaris campus starting this weekend. Budget is 14k-18k. Vegetarian/clean habits. DM or reply ASAP!",
    category_tag: "SOS Query",
    upvotes_count: 39,
    timestamp: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    is_sos: true,
    is_anonymous: true,
    answers: [
      {
        id: "ans-polaris-1",
        post_id: "polaris-post-3",
        user_name: "Rohan K (Term 3)",
        user_role_tag: "student",
        content: "One single room just freed up in our flat at 17th Cross HSR, 10 min electric scooter ride from campus. DM on WhatsApp +91-9876543210 immediately.",
        upvotes_count: 28,
        timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
        is_accepted: true,
      }
    ]
  },
  {
    id: "polaris-post-4",
    campus_id: "polaris-blr",
    user_name: "Dev Patel",
    user_role_tag: "student",
    title: "Lost: Apple Pencil 2 with engraved initials 'DP' in Design Studio",
    content: "Accidentally left it plugged into the iPad charging dock in studio 3B yesterday night. Reward offered if returned!",
    category_tag: "Lost & Found",
    upvotes_count: 18,
    timestamp: new Date(Date.now() - 1000 * 60 * 400).toISOString(),
    is_sos: false,
    is_anonymous: false,
  },

  // Stanford University Posts
  {
    id: "stanford-post-1",
    campus_id: "stanford-us",
    user_name: "Stanford Provost Office",
    user_role_tag: "admin",
    title: "Official Alert: Spring Semester Grant Applications Open for Open-Source Research",
    content: "Undergraduate and graduate research grants up to $15,000 per project are now open for applicants working on decentralized inference and trustworthy generative models.",
    category_tag: "Official Alert",
    upvotes_count: 145,
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    is_sos: false,
    is_anonymous: false,
  },
  {
    id: "stanford-post-2",
    campus_id: "stanford-us",
    user_name: "Anonymous Student",
    user_role_tag: "student",
    title: "SOS: Anyone taking CS229 Machine Learning this quarter with Prof. Ng?",
    content: "Forming an emergency study group for problem set 2 due Thursday midnight. Meeting at Gates Hall basement or Discord.",
    category_tag: "SOS Query",
    upvotes_count: 51,
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    is_sos: true,
    is_anonymous: true,
    answers: []
  },

  // IIT Bombay Posts
  {
    id: "iitb-post-1",
    campus_id: "iitb-mum",
    user_name: "Mood Indigo Core Committee",
    user_role_tag: "club",
    title: "Mood Indigo 2026: Campus Ambassador Program & Pro-Nite Passes",
    content: "The biggest college cultural festival in Asia is gearing up! Campus Ambassador applications are live with certificate endorsement and all-access passes.",
    category_tag: "Fest/Events",
    upvotes_count: 210,
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    is_sos: false,
    is_anonymous: false,
  },
  {
    id: "iitb-post-2",
    campus_id: "iitb-mum",
    user_name: "Dean of Student Affairs",
    user_role_tag: "admin",
    title: "Official: Campus Electric Shuttle Schedule Revised for Winter Session",
    content: "Additional shuttle loops have been deployed between Hostels 12-16 and Lecture Hall Complex (LHC) during morning peak hours (8:15 AM - 9:30 AM).",
    category_tag: "Official Alert",
    upvotes_count: 98,
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    is_sos: false,
    is_anonymous: false,
  }
];
