import { PlacementStats, CampusReview } from "./review-types";

export const CAMPUS_PLACEMENT_STATS: Record<string, PlacementStats> = {
  "bhopal-node": {
    campus_id: "bhopal-node",
    academic_year: "2025-26 (Ongoing)",
    highest_ctc_lpa: 54.0,
    avg_ctc_lpa: 12.8,
    placement_rate_pct: 86.4,
    total_offers: 940,
    total_eligible_students: 1088,
    top_recruiters: [
      { name: "Microsoft", tier: "Tier-1 Product", avg_package_lpa: 43.5, backlog_criteria: "Strictly 0 active backlogs, CGPA >= 7.5" },
      { name: "Amazon", tier: "Tier-1 Product", avg_package_lpa: 36.0, backlog_criteria: "No active backlogs at time of interview" },
      { name: "Oracle", tier: "Tier-1 Product", avg_package_lpa: 19.5, backlog_criteria: "Max 1 cleared backlog permitted" },
      { name: "Goldman Sachs", tier: "Tier-1 Product", avg_package_lpa: 24.0, backlog_criteria: "Strictly 0 backlogs allowed" },
      { name: "Tata Motors", tier: "Core", avg_package_lpa: 10.5, backlog_criteria: "Cleared backlogs accepted with explanation" },
      { name: "L&T Construction", tier: "Core", avg_package_lpa: 9.0, backlog_criteria: "Max 2 cleared backlogs" },
      { name: "Deloitte", tier: "Consulting", avg_package_lpa: 12.0, backlog_criteria: "No active backlogs allowed" },
    ],
    backlog_trends: {
      zero_backlogs_required_pct: 72,
      cleared_backlogs_allowed_pct: 21,
      active_backlogs_allowed_pct: 7,
      policy_summary: "Tier-1 tech companies enforce strict zero active backlog filters during online screening tests. However, 28% of visiting companies permit students with previously cleared backlogs as long as current CGPA exceeds 6.5.",
      critical_advice: "Clear all semester arrears before the 7th-semester placement season starts in August. Companies verify grade cards right before issuing offer letters.",
    },
    past_years_comparison: [
      { year: "2024-25", highest_ctc_lpa: 52.5, avg_ctc_lpa: 11.9, placement_rate_pct: 88.2, total_offers: 1020 },
      { year: "2023-24", highest_ctc_lpa: 48.0, avg_ctc_lpa: 10.5, placement_rate_pct: 84.0, total_offers: 890 },
      { year: "2022-23", highest_ctc_lpa: 44.0, avg_ctc_lpa: 9.8, placement_rate_pct: 82.5, total_offers: 810 },
    ],
  },
  "polaris-blr": {
    campus_id: "polaris-blr",
    academic_year: "2025-26 (Cohort Sprint)",
    highest_ctc_lpa: 48.0,
    avg_ctc_lpa: 18.5,
    placement_rate_pct: 94.2,
    total_offers: 165,
    total_eligible_students: 175,
    top_recruiters: [
      { name: "CRED", tier: "High-Growth Tech", avg_package_lpa: 26.0, backlog_criteria: "Proof-of-work and GitHub contributions prioritized over backlogs" },
      { name: "Razorpay", tier: "High-Growth Tech", avg_package_lpa: 24.5, backlog_criteria: "No active backlogs in core CS subjects" },
      { name: "Postman", tier: "High-Growth Tech", avg_package_lpa: 28.0, backlog_criteria: "Zero active backlogs at time of joining" },
      { name: "Polygon / Solana Labs", tier: "High-Growth Tech", avg_package_lpa: 35.0, backlog_criteria: "Open criteria - evaluated purely on codebase audit" },
      { name: "BrowserStack", tier: "High-Growth Tech", avg_package_lpa: 20.0, backlog_criteria: "Max 1 cleared backlog" },
    ],
    backlog_trends: {
      zero_backlogs_required_pct: 45,
      cleared_backlogs_allowed_pct: 40,
      active_backlogs_allowed_pct: 15,
      policy_summary: "Because Polaris focuses on project-driven software engineering and industry bootcamps, over 55% of hiring partners emphasize open-source repositories and system design assessments over academic backlog history.",
      critical_advice: "Maintain strong pull requests on GitHub. Startups and series-B tech firms visiting campus will overlook minor academic delays if your production projects are exceptional.",
    },
    past_years_comparison: [
      { year: "2024-25", highest_ctc_lpa: 45.0, avg_ctc_lpa: 17.2, placement_rate_pct: 92.0, total_offers: 140 },
      { year: "2023-24", highest_ctc_lpa: 38.0, avg_ctc_lpa: 15.0, placement_rate_pct: 90.0, total_offers: 120 },
    ],
  },
  "iitb-mum": {
    campus_id: "iitb-mum",
    academic_year: "2025-26 (Phase 1)",
    highest_ctc_lpa: 168.0,
    avg_ctc_lpa: 23.5,
    placement_rate_pct: 91.0,
    total_offers: 1350,
    total_eligible_students: 1480,
    top_recruiters: [
      { name: "Jane Street / Citadel", tier: "Tier-1 Product", avg_package_lpa: 120.0, backlog_criteria: "Zero history of backlogs, CPI >= 8.5" },
      { name: "Google", tier: "Tier-1 Product", avg_package_lpa: 48.0, backlog_criteria: "Zero active backlogs" },
      { name: "McKinsey & Co", tier: "Consulting", avg_package_lpa: 30.0, backlog_criteria: "No active backlogs allowed" },
      { name: "Qualcomm", tier: "Core", avg_package_lpa: 28.0, backlog_criteria: "Cleared backlogs permitted" },
    ],
    backlog_trends: {
      zero_backlogs_required_pct: 85,
      cleared_backlogs_allowed_pct: 12,
      active_backlogs_allowed_pct: 3,
      policy_summary: "High-frequency trading firms and top consulting leaders strictly filter out any student with a backlog history. Core engineering firms offer slightly more flexibility.",
      critical_advice: "CPI below 7.0 or having any active backlog will block you from Phase-1 Day 1 slots. Prioritize backlog clearance in the summer re-exam slot.",
    },
    past_years_comparison: [
      { year: "2024-25", highest_ctc_lpa: 150.0, avg_ctc_lpa: 22.0, placement_rate_pct: 92.5, total_offers: 1400 },
      { year: "2023-24", highest_ctc_lpa: 140.0, avg_ctc_lpa: 20.8, placement_rate_pct: 89.0, total_offers: 1280 },
    ],
  },
};

export const INITIAL_CAMPUS_REVIEWS: CampusReview[] = [
  {
    id: "rev-1",
    campus_id: "bhopal-node",
    student_id: "std-bhopal-01",
    student_name: "Karan Johar",
    student_roll_prefix: "2111120XX",
    branch: "Computer Science & Engineering",
    grad_year: 2025,
    is_verified: true,
    overall_rating: 4,
    academics_rating: 4,
    infrastructure_rating: 3,
    placement_rating: 5,
    review_title: "Solid placement cell, but clear your backlogs early!",
    review_text: "The placement season here is intense. Almost 60+ tech companies visited by October. If you have clean DSA fundamentals and no active backlogs, you have a 90% shot at getting placed in a 10+ LPA package. The library is open 24/7 during exam weeks.",
    pros: "Top product companies visit, vibrant coding clubs, low tuition fees compared to private colleges.",
    cons: "Hostel mess food can be hit-or-miss, and administrative red tape for document verification is slow.",
    visiting_companies_experienced: ["Microsoft", "Oracle", "Amazon", "JPMorgan Chase"],
    backlog_advice: "I had 1 backlog in Digital Electronics in 3rd sem. I worked hard and cleared it in the supplementary round before 7th sem. Oracle and TCS still let me sit because it was cleared. Don't panic, just clear it before the August placement freeze!",
    upvotes_count: 42,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), // 3 days ago
  },
  {
    id: "rev-2",
    campus_id: "bhopal-node",
    student_id: "std-bhopal-02",
    student_name: "Sneha Patel",
    student_roll_prefix: "2211150XX",
    branch: "Electronics & Communication",
    grad_year: 2026,
    is_verified: true,
    overall_rating: 4,
    academics_rating: 4,
    infrastructure_rating: 4,
    placement_rating: 4,
    review_title: "Great campus environment and active technical societies",
    review_text: "Campus life is very balanced between academics and extracurriculars. The technical fests attract students from all over central India. Professors in ECE are research-focused and encourage IEEE publications.",
    pros: "High lab access, great peer group, active robotics society.",
    cons: "Bus schedule from south Bhopal can get crowded during morning rush.",
    visiting_companies_experienced: ["Qualcomm", "Texas Instruments", "Tata Motors"],
    backlog_advice: "Core semiconductor firms like TI and Qualcomm check your Analog and Signals grades very closely. Having a backlog in basic circuit theory will immediately disqualify you from their shortlist.",
    upvotes_count: 27,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: "rev-3",
    campus_id: "polaris-blr",
    student_id: "std-polaris-01",
    student_name: "Arjun Mehta",
    student_roll_prefix: "POL-2023-04X",
    branch: "Applied AI & Full-Stack Systems",
    grad_year: 2026,
    is_verified: true,
    overall_rating: 5,
    academics_rating: 5,
    infrastructure_rating: 5,
    placement_rating: 5,
    review_title: "Hyper-practical curriculum tailored for real Bangalore startup ecosystem",
    review_text: "Zero rote memorization. We deploy real systems to production from month two. Hiring managers from CRED, Swiggy, and Razorpay mentor us directly every month. The stipend offers during internships are already comparable to entry-level salaries elsewhere.",
    pros: "World-class hardware and AI workstations, 1-on-1 industry mentors, direct pipeline to funded tech startups.",
    cons: "Rigorous schedule with 40+ hours of weekly sprint work, requires high self-discipline.",
    visiting_companies_experienced: ["CRED", "Razorpay", "Postman", "BrowserStack"],
    backlog_advice: "Polaris evaluates based on project milestones rather than conventional exam marks. If you struggle with a sprint module, you can redo the project deliverable during the revision week without an academic penalty on your transcript.",
    upvotes_count: 59,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
];
